name: Update schema files when api changes

on:
  push:
    branches:
      - master
    paths:
      - 'apps/**'
      - 'policy/**'
      - 'rollouts/**'

jobs:
  update-schemas:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Update Schema
        run: |
          go mod tidy
          make gen-openapi-schema
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated OpenAPI schema files